In [64]:

import pandas as pd

In [65]:
data = {
    'date': ['2021-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country': ['USA', 'U.S.A.', 'America', 'United States'],
    'name': ['John Doe', 'Jonh Doe', 'Jane Doe', 'Jane Doe'],
    'sales_2020': [100, 200, None, 200],
    'sales_2021': [None, 150, 300, 150]
}

 # make it pandas dataframe
df = pd.DataFrame(data)

In [55]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1  01-12-2022         U.S.A.  Jonh Doe       200.0       150.0
2  2022/12/01        America  Jane Doe         NaN       300.0
3  12-01-2021  United States  Jane Doe       200.0       150.0

In [66]:
# standardize the date format
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1         NaN         U.S.A.  Jonh Doe       200.0       150.0
2         NaN        America  Jane Doe         NaN       300.0
3         NaN  United States  Jane Doe       200.0       150.0

# impute fill the date and try another method to complete the date format inconsistencies

In [67]:
import pandas as pd

# Convert mixed date formats
df['date'] = pd.to_datetime(df['date'], format='mixed')

# Convert to one standard format
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

print(df)

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1         NaN         U.S.A.  Jonh Doe       200.0       150.0
2         NaN        America  Jane Doe         NaN       300.0
3         NaN  United States  Jane Doe       200.0       150.0

In [62]:
df['date'] = pd.to_datetime(df['date'], format='mixed')
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df['date'] = df['date'].ffill()
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-01-12            USA  John Doe       100.0         NaN
1  2021-01-12         U.S.A.  Jonh Doe       200.0       150.0
2  2021-01-12        America  Jane Doe         NaN       300.0
3  2021-01-12  United States  Jane Doe       200.0       150.0

In [39]:
# harmonize the country names
country_mapping = {'USA': 'United States', 'U.S.A.': 'United States', 'America': 'United States'}
df['country'] = df['country'].replace(country_mapping)

In [40]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01  United States  John Doe       100.0         NaN
1         NaN  United States  Jonh Doe       200.0       150.0
2         NaN  United States  Jane Doe         NaN       300.0
3         NaN  United States  Jane Doe       200.0       150.0

In [43]:
# correct the typographical Mistakes in he names
# let's assume we want to correct the name 'jonh Doe' to 'John Doe'
df['name'] = df['name'].replace({'Jonh Doe': 'John Doe'})
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01  United States  John Doe       100.0         NaN
1         NaN  United States  John Doe       200.0       150.0
2         NaN  United States  Jane Doe         NaN       300.0

In [44]:
# remove the duplicate 
df = df.drop_duplicates(subset= 'name')
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01  United States  John Doe       100.0         NaN
2         NaN  United States  Jane Doe         NaN       300.0

In [46]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1  01-12-2022         U.S.A.  Jonh Doe       200.0       150.0
2  2022/12/01        America  Jane Doe         NaN       300.0
3  12-01-2021  United States  Jane Doe       200.0       150.0

In [47]:
# 5. resolving Contradictory Data
# For demonstration, let's assumeding sales_2021 should always be greater than sales_2020. We can remove rows where this is not the case. 
df = df.drop(df[df['sales_2021'] <= df['sales_2020']].index)

In [48]:
df.head()

         date  country      name  sales_2020  sales_2021
0  2021-12-01      USA  John Doe       100.0         NaN
2  2022/12/01  America  Jane Doe         NaN       300.0