# Dat Merge

In [3]:
import pandas as pd

# example datasets for data merging
# dataset 1:  Pakistani Individuals
data1 = {
    'id' : [1,2,3],
    'name' : ['Ahmed', 'Fatima', 'Ali'],
    'age' : [28, 32, 24]
}
df1 = pd.DataFrame(data1)
df1

   id    name  age
0   1   Ahmed   28
1   2  Fatima   32
2   3     Ali   24

In [4]:
# Dataset 2: Additional information
data2 = {
    'id' : [1,2,4],
    'city' : ['Karachi', 'Lahore', 'Islamabad'],
    'occupation' : ['Engineer', 'Doctor', 'Teacher']
}
df2 = pd.DataFrame(data2)
df2

   id       city occupation
0   1    Karachi   Engineer
1   2     Lahore     Doctor
2   4  Islamabad    Teacher

In [6]:
# merging the dataframes on 'id'
merged_df = pd.merge(df1, df2, on= 'id' ,  how = 'inner')
merged_df

   id    name  age     city occupation
0   1   Ahmed   28  Karachi   Engineer
1   2  Fatima   32   Lahore     Doctor

In [7]:
# merging the dataframes on 'id'
merged_df = pd.merge(df1, df2, on= 'id' ,  how = 'outer')
merged_df

   id    name   age       city occupation
0   1   Ahmed  28.0    Karachi   Engineer
1   2  Fatima  32.0     Lahore     Doctor
2   3     Ali  24.0        NaN        NaN
3   4     NaN   NaN  Islamabad    Teacher

In [8]:
# merging the dataframes on 'id'
merged_df = pd.merge(df1, df2, on= 'id' ,  how = 'left')
merged_df

   id    name  age     city occupation
0   1   Ahmed   28  Karachi   Engineer
1   2  Fatima   32   Lahore     Doctor
2   3     Ali   24      NaN        NaN

In [9]:
# merging the dataframes on 'id'
merged_df = pd.merge(df1, df2, on= 'id' ,  how = 'right')
merged_df

   id    name   age       city occupation
0   1   Ahmed  28.0    Karachi   Engineer
1   2  Fatima  32.0     Lahore     Doctor
2   4     NaN   NaN  Islamabad    Teacher

# Data Concatination

In [14]:
import pandas as pd

# example datasets for Pakistani Context
# dataset 1:  Pakistani and ages
data1 = {
   
    'Name' : ['Ahmed', 'Fatima', 'Ali'],
    'Age' : [28, 32, 24]
}

# Data 2 : Pakistani and ages
data2 = {
   
    'Name' : ['Sara', 'Usman', 'Aisha'],
    'Age' : [29, 35, 27]
}

# Dataset 3: Additional information
data3 = {
   
    'City' : ['Karachi', 'Lahore', 'Islamabad'],
    'Province' : ['Sindh', 'Punjab', 'Islamabad']
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

# Concatenating the Rows
concatenated_rows = pd.concat([df1, df2], axis = 0)

#concatenating columns
# Note: For a meaningful column-wise  concatenation , dataframe should have the same
concatenated_columns = pd.concat([df1, df3],  axis=1)

print(concatenated_rows)

print("-------------------")

concatenated_columns

     Name  Age
0   Ahmed   28
1  Fatima   32
2     Ali   24
0    Sara   29
1   Usman   35
2   Aisha   27
-------------------

     Name  Age       City   Province
0   Ahmed   28    Karachi      Sindh
1  Fatima   32     Lahore     Punjab
2     Ali   24  Islamabad  Islamabad