# Feature Scaling

In [ ]:
#pip install scikit-learn

## 1. "Min Max Scaling"

In [6]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Sample data
data = {'Value': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

df.head()

   Value
0     10
1     20
2     30
3     40
4     50

In [7]:
# scale the data using min max scaler

# Min-Max Scaling
scaler = MinMaxScaler()
df['Scaled_Value'] = scaler.fit_transform(df['Value'].values.reshape(-1,1))
df.head()

   Value  Scaled_Value
0     10          0.00
1     20          0.25
2     30          0.50
3     40          0.75
4     50          1.00

In [8]:

# Min-Max Scaling
scaler = MinMaxScaler()
df['Scaled_Value'] = scaler.fit_transform(df[['Value']])
print(df)

   Value  Scaled_Value
0     10          0.00
1     20          0.25
2     30          0.50
3     40          0.75
4     50          1.00

# 2. Standard Scaler or Z-score normalozation

In [10]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Sample data
data = {'Value': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

df.head()

   Value
0     10
1     20
2     30
3     40
4     50

In [12]:
# Stabdard Scaling
scaler = StandardScaler()
df['Scaled_Value'] = scaler.fit_transform(df[['Value']])
df.head()

   Value  Scaled_Value
0     10     -1.414214
1     20     -0.707107
2     30      0.000000
3     40      0.707107
4     50      1.414214

# 3. Robust Scaler

In [15]:
import pandas as pd
from sklearn.preprocessing import RobustScaler

# Sample data  with outliers
data = {'Value': [10, 20, 30, 1000, 50]}
df = pd.DataFrame(data)

# Robust Scaling
scaler= RobustScaler()
df['Scaler_Value'] = scaler.fit_transform(df[['Value']])
print(df)

   Value  Scaler_Value
0     10     -0.666667
1     20     -0.333333
2     30      0.000000
3   1000     32.333333
4     50      0.666667

# 4. logrithmic Scaling /Normalization

In [19]:
# import libraries
import numpy as np
import pandas as pd

# random data 
data = {'Value': [10000, 20000, 30000, 100000, 50000]}
df = pd.DataFrame(data)

# log Tranform
df['scaled_value'] =  np.log(df['Value'])
df['scaled_value10'] =  np.log10(df['Value'])
df['scaled_value2'] =  np.log2(df['Value'])

df.head()

    Value  scaled_value  scaled_value10  scaled_value2
0   10000      9.210340        4.000000      13.287712
1   20000      9.903488        4.301030      14.287712
2   30000     10.308953        4.477121      14.872675
3  100000     11.512925        5.000000      16.609640
4   50000     10.819778        4.698970      15.609640